name: 'C++ CI'

on:
  push:
    branches:
      - master
      - '**' 

jobs:
  release:
    if: github.ref == 'refs/heads/master' # Only run on master branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev ninja-build libgtest-dev -y
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_GTEST=ON -G Ninja
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "*.deb"
          makeLatest: true

  # Non-master build scenario without packaging and release
  build-and-test:
    if: github.ref != 'refs/heads/master' # Run on non-master branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev ninja-build libgtest-dev -y
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON -G Ninja
      - run: cmake --build .
      - run: cmake --build . --target test
